[supervisord]
nodaemon=true
logfile=/dev/null
loglevel=info

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:5000 --workers=1 --threads=2 app:app
autostart=true
autorestart=true
stderr_logfile=/dev/null
stdout_logfile=/dev/null
redirect_stderr=true
loglevel=info
maxbytes=0

[program:celery]
command=celery -A app.celery worker --loglevel=info --concurrency=1
autostart=true
autorestart=true
stderr_logfile=/dev/null
stdout_logfile=/dev/null
redirect_stderr=true
loglevel=info
maxbytes=0

[program:redis]
command=redis-server --port 6379
autostart=true
autorestart=true
stderr_logfile=/dev/null
stdout_logfile=/dev/null
redirect_stderr=true
loglevel=info
maxbytes=0
